version: 2
env:
  - CGO_ENABLED=0

builds:
  - binary: "{{ .ProjectName }}_v{{ .Version }}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

    ldflags:
      - "-s -w -X main.version={{.Version}}"

    goos:
      - darwin
      - freebsd
      - linux
      - windows

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm

archives:
  - formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

changelog:
  disable: true
